// LHIND role catalogue — generated from the official role/synonym list.
// `name` is the searchable display label; `base` is the role family.
// Used by the onboarding role picker (searchable + free text).

export const LHIND_ROLES = [
  { name: ".NET Developer", base: "Software Developer" },
  { name: "Account Manager", base: "n/a" },
  { name: "Agile Coach", base: "Agile Coach" },
  { name: "Agile Manager", base: "Agile Coach" },
  { name: "Agile Trainer", base: "Agile Coach" },
  { name: "Agile Transformation Manager", base: "Agile Coach" },
  { name: "AI Automation Engineer", base: "DevOps Engineer" },
  { name: "AI Business Advisor", base: "Consultant" },
  { name: "AI Champion", base: "Consultant" },
  { name: "AI Engineer", base: "AI Engineer" },
  { name: "Application Management Service Consultant", base: "Consultant" },
  { name: "Application Manager", base: "Service Manager" },
  { name: "Application Operation & Support Specialist", base: "Application Engineer" },
  { name: "Application Operations", base: "Application Engineer" },
  { name: "Application Owner", base: "Service Manager" },
  { name: "Application Production Support", base: "Application Engineer" },
  { name: "Associate Consultant", base: "Consultant" },
  { name: "Auditor", base: "Governance Manager" },
  { name: "Auditor ISO 27001", base: "Governance Manager" },
  { name: "Auditor TISAX", base: "Governance Manager" },
  { name: "Backend Architect / Engineer", base: "Architect" },
  { name: "Backend Developer", base: "Software Developer" },
  { name: "Backoffice", base: "n/a" },
  { name: "BI Developer", base: "n/a" },
  { name: "BI Reporting & Analytics Consultant", base: "Consultant" },
  { name: "BI Solution Architect", base: "Data Architect" },
  { name: "BI Solutions Consultant", base: "Business Analyst" },
  { name: "Business Analyst", base: "Business Analyst" },
  { name: "Business Consultant", base: "Consultant" },
  { name: "Business Continuity Manager", base: "Governance Manager" },
  { name: "Business Information Security Officer (BISO)", base: "Governance Manager" },
  { name: "Business Owner", base: "n/a" },
  { name: "Business Process Manager", base: "n/a" },
  { name: "Celonis Consultant", base: "Consultant" },
  { name: "Celonis Data Analyst", base: "Data Analyst" },
  { name: "Celonis Data Engineer", base: "Data Engineer" },
  { name: "Change Manager", base: "Service Manager" },
  { name: "Change Request Manager", base: "Architect" },
  { name: "Cloud Architect", base: "Infrastructure Architect" },
  { name: "Cloud DevOps Architect", base: "Infrastructure Architect" },
  { name: "Cloud DevOps Engineer", base: "Infrastructure Engineer" },
  { name: "Cloud Engineer", base: "Infrastructure Engineer" },
  { name: "Cloud Native Architect", base: "Infrastructure Architect" },
  { name: "Cloud Native Developer", base: "Platform Developer" },
  { name: "CMDB Configuration Management & Architecture Member", base: "Service Manager" },
  { name: "Compliance Officer / Software Compliance Manager", base: "Governance Manager" },
  { name: "Configuration Manager", base: "Service Manager" },
  { name: "Corporate Transformation Consultant", base: "Agile Coach" },
  { name: "Customer Solution Manager", base: "n/a" },
  { name: "Customer Value Manager", base: "n/a" },
  { name: "Data Analyst", base: "Data Analyst" },
  { name: "Data Architect", base: "Data Architect" },
  { name: "Data Engineer", base: "Data Engineer" },
  { name: "Data Governance Consultant", base: "Consultant" },
  { name: "Data Modelling Specialist", base: "Data Engineer" },
  { name: "Data Platform Engineer", base: "Platform Engineer" },
  { name: "Data Protection Consultant", base: "Governance Manager" },
  { name: "Data Protection Manager", base: "Governance Manager" },
  { name: "Data Science & Artificial Intelligence Consultant", base: "Consultant" },
  { name: "Data Scientist", base: "Data Scientist" },
  { name: "Database Administrator", base: "Infrastructure Administrator" },
  { name: "Database Architect", base: "Infrastructure Architect" },
  { name: "Database Developer", base: "Infrastructure Engineer" },
  { name: "Database Engineer", base: "Infrastructure Engineer" },
  { name: "Developer for Microsoft Dynamics 365 Finance&Supply Chain Management", base: "Platform Developer" },
  { name: "DevOps Architect", base: "Architect" },
  { name: "DevOps Engineer", base: "DevOps Engineer" },
  { name: "DevOps Manager", base: "DevOps Engineer" },
  { name: "Digital Product Analyst", base: "Consultant" },
  { name: "Digital Strategist", base: "Consultant" },
  { name: "Dual Student", base: "n/a" },
  { name: "Dynamics 365 BC Architect", base: "Platform Architect" },
  { name: "Dynamics 365 BC Consultant", base: "Consultant" },
  { name: "Dynamics 365 BC Engineer", base: "Platform Engineer" },
  { name: "Dynamics 365 CRM Architect", base: "Platform Architect" },
  { name: "Dynamics 365 CRM Consultant", base: "Consultant" },
  { name: "Dynamics 365 CRM Engineer", base: "Platform Engineer" },
  { name: "Dynamics 365 Finance & Supply Chain Management Architect", base: "Platform Architect" },
  { name: "Dynamics 365 Finance & Supply Chain Management Consultant", base: "Consultant" },
  { name: "Dynamics 365 Finance & Supply Chain Management Engineer", base: "Platform Engineer" },
  { name: "Enterprise Architect", base: "Architect" },
  { name: "Enterprise Architecture Management Consultant", base: "Architect" },
  { name: "Enterprise Integration Architect", base: "Platform Architect" },
  { name: "Enterprise Integration Developer", base: "Platform Developer" },
  { name: "Enterprise Integration Engineer", base: "Platform Engineer" },
  { name: "Front End Architect / Engineer", base: "Architect" },
  { name: "Front End Developer", base: "Software Developer" },
  { name: "Fullstack Developer", base: "Software Developer" },
  { name: "Fullstack Software Architect / Engineer", base: "Architect" },
  { name: "Functional Project Manager", base: "Project Manager" },
  { name: "Functional Test Engineer", base: "Test Engineer" },
  { name: "GenAI Engineer", base: "Data Engineer" },
  { name: "Governance Manager", base: "Governance Manager" },
  { name: "Head of Platform Engineering", base: "n/a" },
  { name: "HR IT Consultant", base: "n/a" },
  { name: "Hunting & Forensic Expert", base: "n/a" },
  { name: "Incident Manager", base: "Service Manager" },
  { name: "Incident Solver", base: "Service Desk Agent" },
  { name: "Information Security Officer", base: "Governance Manager" },
  { name: "Innovation Management", base: "Consultant" },
  { name: "Inside Sales Manager", base: "n/a" },
  { name: "Intelligent Process Automation Consultant", base: "Consultant" },
  { name: "IoT Architect", base: "Infrastructure Architect" },
  { name: "IoT Engineer Backend & Analytics", base: "Infrastructure Engineer" },
  { name: "IoT Engineer Edge & Sensorik & Communication", base: "Infrastructure Engineer" },
  { name: "IoT Engineer Operational Technologies", base: "Infrastructure Engineer" },
  { name: "IoT Platform & Data Architect", base: "Infrastructure Architect" },
  { name: "IoT Platform & Data Developer", base: "Infrastructure Developer" },
  { name: "IT Demand Manager", base: "n/a" },
  { name: "IT Network Admin", base: "Infrastructure Architect" },
  { name: "IT Network Manager", base: "Infrastructure Architect" },
  { name: "IT Operation Expert", base: "Service Manager" },
  { name: "IT Operations Manager", base: "Service Manager" },
  { name: "IT Security Architect", base: "Security Architect" },
  { name: "IT Security Engineer", base: "Security Engineer" },
  { name: "IT Security Manager (ISMS)", base: "Governance Manager" },
  { name: "IT Service Continuity Manager", base: "Governance Manager" },
  { name: "IT Service Owner", base: "Service Manager" },
  { name: "IT Software Engineer", base: "Software Developer" },
  { name: "IT Strategist", base: "Consultant" },
  { name: "IT Support Specialist", base: "Service Desk Agent" },
  { name: "IT Systems Analyst", base: "Business Analyst" },
  { name: "IT-Security Administrator", base: "Security Administrator" },
  { name: "IT-Security Analyst", base: "Security Analyst" },
  { name: "IT-Security Risk Manager", base: "Governance Manager" },
  { name: "IT-Security Social Engineer", base: "Security Engineer" },
  { name: "Jira Administrator / Consultant", base: "Platform Developer" },
  { name: "Jira Service Management (JSM) Administrator / Consultant", base: "Platform Developer" },
  { name: "Lead Platform Engineer", base: "Platform Engineer" },
  { name: "LHIND Manager", base: "n/a" },
  { name: "M365 Architect", base: "Platform Architect" },
  { name: "M365 Developer", base: "Platform Developer" },
  { name: "M365 Engineer", base: "Platform Engineer" },
  { name: "Manager On-Call", base: "Service Manager" },
  { name: "Mendix Developer / Engineer", base: "Platform Developer" },
  { name: "Microsoft 365 Consultant", base: "Consultant" },
  { name: "Microsoft Consultant", base: "Consultant" },
  { name: "Mobile Developer", base: "Software Developer" },
  { name: "Mobile Software Architect", base: "Architect" },
  { name: "Network Administrator", base: "Infrastructure Administrator" },
  { name: "Network Engineer", base: "Infrastructure Engineer" },
  { name: "Network Specialist", base: "Infrastructure Engineer" },
  { name: "NOC Engineer", base: "Infrastructure Engineer" },
  { name: "Offensive Security Consultant", base: "Consultant" },
  { name: "Operator", base: "Service Desk Agent" },
  { name: "Organizational Design Consultant", base: "Consultant" },
  { name: "Penetration Test Engineer", base: "Test Engineer" },
  { name: "Platform Engineer", base: "Platform Engineer" },
  { name: "PMO Lead", base: "Project Manager" },
  { name: "Portfolio Manager", base: "n/a" },
  { name: "Power Platform Architect", base: "Platform Architect" },
  { name: "Power Platform Consultant", base: "Consultant" },
  { name: "Power Platform Engineer", base: "Platform Engineer" },
  { name: "Pre-Sales Support", base: "n/a" },
  { name: "Privacy Champion", base: "n/a" },
  { name: "Privacy Manager", base: "Governance Manager" },
  { name: "Problem Manager", base: "Service Manager" },
  { name: "Process Manager", base: "Governance Manager" },
  { name: "Process Owner", base: "n/a" },
  { name: "Product Business Owner", base: "n/a" },
  { name: "Product Consulting", base: "Consultant" },
  { name: "Product Controlling", base: "n/a" },
  { name: "Product Customer Success Manager", base: "n/a" },
  { name: "Product Manager", base: "Product Manager" },
  { name: "Product Marketing Specialist", base: "n/a" },
  { name: "Product Owner", base: "Product Owner" },
  { name: "Product Owner SAFe", base: "Product Owner" },
  { name: "Product Sales", base: "n/a" },
  { name: "Product Social Media Manager", base: "n/a" },
  { name: "Program Manager", base: "Project Manager" },
  { name: "Project Assistant", base: "Project Manager" },
  { name: "Project Management Office Consultant (PMO)", base: "Project Manager" },
  { name: "Project Manager / Project Lead", base: "Project Manager" },
  { name: "Provider Manager", base: "Governance Manager" },
  { name: "Proxy Product Owner", base: "Product Owner" },
  { name: "Quality Manager", base: "Governance Manager" },
  { name: "Quality Manager Architecture & Coding", base: "Architect" },
  { name: "Release Manager", base: "Service Manager" },
  { name: "Release Train Engineer", base: "Scrum Master" },
  { name: "Requirements Engineer", base: "Business Analyst" },
  { name: "Resource Manager", base: "n/a" },
  { name: "Risk Manager", base: "Governance Manager" },
  { name: "Rollout Manager", base: "n/a" },
  { name: "SAFe Coach / Transformation Manager", base: "Agile Coach" },
  { name: "SAFe Trainer", base: "Agile Coach" },
  { name: "Sales Manager", base: "n/a" },
  { name: "Salesforce Architect", base: "Platform Architect" },
  { name: "Salesforce Consultant", base: "Consultant" },
  { name: "Salesforce Developer", base: "Platform Developer" },
  { name: "SAP Consultant", base: "Consultant" },
  { name: "SAP Developer", base: "Platform Developer" },
  { name: "SAP Project Lead", base: "Project Manager" },
  { name: "SAP Trainer", base: "Consultant" },
  { name: "Scrum Master", base: "Scrum Master" },
  { name: "Scrum Master SAFe", base: "Scrum Master" },
  { name: "Security Champion", base: "n/a" },
  { name: "Security Manager", base: "Governance Manager" },
  { name: "Security Project Lead", base: "Project Manager" },
  { name: "Security Service Manager", base: "Service Manager" },
  { name: "Segment Delivery Manager", base: "Service Manager" },
  { name: "Service Delivery Manager", base: "Service Manager" },
  { name: "Service Manager", base: "Service Manager" },
  { name: "Service Portfolio & Catalogue Manager", base: "Service Manager" },
  { name: "Service Technology Consultant", base: "Consultant" },
  { name: "ServiceNow Administrator", base: "Platform Developer" },
  { name: "ServiceNow Architect", base: "Platform Architect" },
  { name: "ServiceNow Consultant", base: "Consultant" },
  { name: "ServiceNow Developer", base: "Platform Developer" },
  { name: "SharePoint Architect", base: "Platform Architect" },
  { name: "SharePoint Consultant", base: "Consultant" },
  { name: "SharePoint Engineer", base: "Platform Engineer" },
  { name: "Site Reliability Engineer (SRE)", base: "Application Engineer" },
  { name: "Software Engineer", base: "Software Developer" },
  { name: "Software Test Engineer", base: "Test Engineer" },
  { name: "Software Tester (Manual)", base: "Tester" },
  { name: "Solution Architect", base: "Architect" },
  { name: "Solutions Architect", base: "Architect" },
  { name: "Storage Administrator", base: "Infrastructure Administrator" },
  { name: "Storage Engineer", base: "Infrastructure Engineer" },
  { name: "Strategy Consultant", base: "Consultant" },
  { name: "Sub-Project Leader", base: "Project Manager" },
  { name: "Sustainability Consultant", base: "Consultant" },
  { name: "System Administrator", base: "Infrastructure Administrator" },
  { name: "System Engineer", base: "Infrastructure Engineer" },
  { name: "System Operation Specialist", base: "Application Engineer" },
  { name: "Systems Administrator", base: "Infrastructure Administrator" },
  { name: "Systems Architect", base: "Infrastructure Architect" },
  { name: "Systems Engineer", base: "Infrastructure Engineer" },
  { name: "Tech-Transformation Manager", base: "Agile Coach" },
  { name: "Technical Consultant", base: "Consultant" },
  { name: "Technical Project Manager", base: "Project Manager" },
  { name: "Technical Test Engineer", base: "Test Engineer" },
  { name: "Test Automation Engineer", base: "Test Engineer" },
  { name: "Test Manager", base: "Test Manager" },
  { name: "Transformation Manager", base: "Agile Coach" },
  { name: "Transition Manager", base: "Service Manager" },
  { name: "Trend Analytics", base: "Data Analyst" },
  { name: "UI Designer", base: "UI/UX Designer" },
  { name: "UI/UX Designer", base: "UI/UX Designer" },
  { name: "UX Designer", base: "UI/UX Designer" },
  { name: "UX Engineer", base: "UI/UX Designer" },
  { name: "UX Researcher", base: "UI/UX Designer" },
  { name: "UX/UI Manager (Product)", base: "UI/UX Designer" },
  { name: "Voice Engineer", base: "Infrastructure Engineer" },
  { name: "Web Developer", base: "Software Developer" },
  { name: "Workforce Management Consultant", base: "Consultant" },
];
