// ============================================================
// VERSION & RELEASE NOTES
// ------------------------------------------------------------
// You normally do NOT edit this file by hand. The GitHub Actions
// workflow (.github/workflows/release.yml) updates the version and
// prepends a new entry to releases.json on every push to main.
//
// MANUAL OVERRIDE (optional): you can still edit src/releases.json
// directly if you want to fix a title or wording.
//
// VERSION is derived from the newest entry in releases.json, so it
// always stays in sync automatically.
// ============================================================

import releases from "./releases.json";

export const RELEASES = releases;
export const VERSION = releases[0]?.version || "0.0.0";
